<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- CSS -->
    <link rel="stylesheet" href="style.css">


</head>

<body>

    <!-- Passer une variable PHP au fichier .js : -->
    <span id="borderScales" data="<?= $borderScales * 2 ?>"></span>

    <!--  DEBUT DU HEADER -->

    <header>
        <nav class="d-flex justify-content-between">
            <lu class="blocs-nav">
                <li class="nav-item mb-1 me-md-2">Florian Moulu</li>
                <li class="nav-item mb-1 me-md-2">
                    <a href="https://www.linkedin.com/in/florian-moulu-b499a8252" target="blank">
                        <span>
                            <i class="fa-brands fa-linkedin"></i>&nbsp;:&nbsp;
                            <u>Florian Moulu</u>
                        </span>
                    </a>
                </li>
                <li class="nav-item mb-1 me-md-2">
                    <a href="#" target="blank"><u>Portfolio</u>
                    </a>
                </li>
            </lu>

            <img id="profile-pic" class="img-fluid" src="https://media-exp1.licdn.com/dms/image/D5603AQEFoinky52-ng/profile-displayphoto-shrink_800_800/0/1665227950540?e=1671667200&v=beta&t=x56iu5KLO1SV4iFsAnaPOiOrtf0EWQDFX8cPbuLGLmY" alt="">

            <div class="d-flex blocs-nav justify-content-end">

                <lu class="text-end">
                    <li class="nav-item mb-1">florianmoulu75@gmail.com</li>
                    <li class="nav-item mb-1">07 81 69 14 23</li>
                    <li class="nav-item mb-1">Paris</li>
                </lu>

                <lu class="text-end">
                    <li class="nav-item mb-1 ms-2 disabled">
                        <a href="mailto: florianmoulu75@gmail.com"><i class="fa-solid fa-envelope animated tada"></i></a>
                    </li>
                    <li class="nav-item mb-1 ms-2 disabled">
                        <a href="tel:+33781691423 text-decoration-none"><i class="fa-solid fa-phone-flip animated tada"></i></a>
                    </li>
                    <li class="nav-item mb-1 ms-2 disabled"><i class="fa-solid fa-location-dot"></i>
                    </li>
                </lu>

            </div>


        </nav>
    </header>

    <!--  FIN DU HEADER -->

    <!-- DEBUT DU MAIN -->

    <main>

        <h1 id="titre-dev" class="text-center">
            Développeur Web
        </h1>



        <div class="d-flex justify-content-evenly py-3" id="resume">

            <!-- DEBUT BLOC COMPETENCES NUMERIQUES -->
            <div class="colonne d-flex flex-column">
                <section class="blocs flex-grow-1">
                    <h2 class="text-center">Compétences Numériques</h2>
                    <h3 class="text-center">Développement Web&nbsp;:</h3>
                    <div class="mx-4">

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50 ">
                                <span>Javascript&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $javascript ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>PHP&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $php ?>%"></div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>Intégration&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $integration ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>Symfony&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $symfony ?>%"></div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>React&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $react ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>NodeJS&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $node ?>%"></div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>P.O.O.&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $poo ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>Sécurité&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $securite ?>%"></div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>Debug,&nbsp;autonomie&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $debug ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>VSC,&nbsp;Emmet,&nbsp;method.&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $vsc ?>%"></div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <h3 class="text-center">Autres domaines</h3>

                    <div class="mx-4">

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>UI Design&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $ui ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>UX Design&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $ux ?>%"></div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>Graphisme&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $graphisme ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>Montage&nbsp;vidéo&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $videoMontage ?>%"></div>
                                </div>
                            </div>
                        </div>


                        <div class="d-flex my-2">
                            <div class="d-flex flex-column w-50">
                                <span>Suite&nbsp;Office&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $office ?>%"></div>
                                </div>
                            </div>
                            <div class="d-flex flex-column w-50">
                                <span>Culture&nbsp;Numérique&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="jauges" style="width: <?= $culture ?>%"></div>
                                </div>
                            </div>
                            
                        </div>


                    </div>
                    <h2 class="text-center"></h2>
                    <h2 class="text-center">Langues</h2>

                    <div class="mx-4">

                        <div class="my-2">
                            <div class="d-flex flex-column w-100">
                                <span>Anglais&nbsp;:</span>
                                <div class="bigScale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="grandeJauges" style="width: <?= $anglais ?>%"></div>
                                </div>
                                <p>
                                    Niveau courant, presque bilingue. Compréhension et expression, à l'oral comme à l'ecrit.
                                </p>
                            </div>
                            <div class="d-flex flex-column w-100">
                                <span>Espagnol&nbsp;:</span>
                                <div class="scale" style="border: solid black <?= $borderScales ?>px;">
                                    <div class="grandeJauges" style="width: <?= $espagnol ?>%"></div>
                                </div>
                                <p>
                                    Bon niveau de compréhension.
                                </p>
                            </div>
                        </div>



                </section>
            </div>
            <!-- FIN BLOC COMPETENCES NUMERIQUES -->

            <!-- DEBUT BLOC COMPETENCES DIVERSES ET EXPERIENCES -->
            <div class="colonne d-flex flex-column justify-content-between">
                <section class="blocs text-center flex-grow-1">
                    <h2>Compétences</h2>
                    <ul>
                        <li>Logique</li>
                        <li>Méthodologie</li>
                        <li>Curiosité</li>
                        <li>Créativité</li>
                        <li>Polyvalence</li>
                        <li>Mémoire de travail</li>
                        <li>Pédagogie/Didactique</li>
                        <li>Esprit d'équipe</li>
                        <li>Adaptabilité</li>
                    </ul>
                </section>


                <section class="blocs flex-grow-1">
                    <h2 class="text-center">Parcours / Expériences</h2>
                    <ul class="list-group list-group-flush mx-4">
                        <li class="list-group-item">
                            <h5>06/22=>02/23&nbsp;:<br>
                                Cursus Paris Code à La Passerelle</h5>
                            Formation intensive et complète au métier de Développement Web :<br>
                            ➡︎ Intégration web <br>
                            ➡︎ JavaScript, React, nodeJS<br>
                            ➡︎ PHP, SQL et Symfony <br>
                            ➡︎ Travail collaboratif avec designers <br>
                            ➡︎ Stage de 3 mois en entreprise
                        </li>
                        <li class="list-group-item">
                            <h5>2018-2022&nbsp;: Entrepreunariat</h5>
                            Projets personnels visant à monétiser mes loisirs et centres d'intérêt et à produire du contenu. <br>
                            Création de contenus relatifs aux jeux-vidéos : Revenus totaux de + de 20 000€. <br>
                            Petits boulots à côté de manière irrégulière
                        </li>
                        <li class="list-group-item">
                            <h5>2017&nbsp;: Licence STAPS</h5>
                            Option Education et Motricité 2nd degré (Pour enseignement en collège/lycée)
                        </li>
                    </ul>
                </section>
            </div>
            <!-- FIN BLOC COMPETENCES DIVERSES ET EXPERIENCES -->

        </div>


    </main>

    <!--  FIN DU MAIN -->

    <footer>

        <p id="hobbies">Centres d'intérêts</p>

        <div id="footer">
            <ul class="nav nav-pills align-items-center justify-content-evenly">
                <li class="nav-item"><i class="fa-solid fa-code"></i></li>
                <li class="nav-item d-flex justify-content-center"><i class="fa-solid fa-gamepad mx-md-2"></i></i><i class="fa-brands fa-steam mx-md-2"></i></li>
                <li class="nav-item"><i class="fa-solid fa-video"></i></li>
                <li class="nav-item"><i class="fa-solid fa-brain mx-md-2"></i><i class="fa-solid fa-user mx-md-2"></i></li>
                <li class="nav-item"><i class="fa-solid fa-futbol"></i></li>
            </ul>

            <ul class="nav nav-pills align-items-center justify-content-evenly">
                <li class="nav-item justify-content-center">Numérique</li>
                <li class="nav-item justify-content-center">Jeux-vidéos</li>
                <li class="nav-item justify-content-center">Séries-TV</li>
                <li class="nav-item justify-content-center">Sciences humaines</li>
                <li class="nav-item justify-content-center">Sport</li>
            </ul>
        </div>

    </footer>

</body>
<script src="index.js"></script>

<!-- Script :
let scale = document.querySelector(".scale")
let bigScale = document.querySelector(".bigScale")

let borderScales = document.getElementById("borderScales").getAttribute('data')

// "scale" correspond à l'espace vide dans lequel la jauge vient s'insérer. On veut savoir la largeur totale.
let largeurMaxJauge = scale.offsetWidth - (borderScales);
let largeurMaxGrandesJauges = bigScale.offsetWidth - (borderScales);
// On créé des tableaux qui serviront avec une boucle for à définir des variables pour chaque jauge.
let jauges = document.querySelectorAll(".jauges")
let grandeJauges = document.querySelectorAll(".grandeJauges")

let r = [];
let g = [];
let largeurJauge = [];

let r2 = [];
let g2 = [];
let largeurGrandeJauge = [];

for (let i = 0; i < jauges.length; i++) {
    // La fonction offsetWidth renvoie la largeur en pixels. On la convertit en pourcentage de remplissage de la barre (scale)
    largeurJauge[i] = (jauges[i].offsetWidth / (largeurMaxJauge / 100))
    // On joue sur les paramètres r et g du rgb pour passer du rouge au vert. Pour des valeurs basses on voudra du rouge + foncé donc on réduit également le paramètre "r".
    if (largeurJauge[i] < 35) {
        r[i] = (130 - (largeurJauge[i] * 1.3))
        g[i] = (0 + (largeurJauge[i] * 1.3))
    } else {
        r[i] = (255 - (largeurJauge[i] * 2.55))
        g[i] = (0 + (largeurJauge[i] * 2.55))
    }
    // On applique finalement le style (couleur et transparence) aux jauges avec les valeurs définies ci-dessus. La transparence commence à 0.75 car des valeurs trop basses renvoient des couleurs claires sur du blanc.
    jauges[i].style.backgroundColor = `rgba(
        ${r[i]},
        ${g[i]},
        0,
        ${0.75 + (largeurJauge[i] / 400)}
        )`;
}

for (let i = 0; i < grandeJauges.length; i++) {
    // La fonction offsetWidth renvoie la largeur en pixels. On la convertit en pourcentage de remplissage de la barre (scale)
    largeurGrandeJauge[i] = (grandeJauges[i].offsetWidth / (largeurMaxGrandesJauges / 100))
    // On joue sur les paramètres r et g du rgb pour passer du rouge au vert. Pour des valeurs basses on voudra du rouge + foncé donc on réduit également le paramètre "r".
    if (largeurGrandeJauge[i] < 35) {
        r2[i] = (130 - (largeurGrandeJauge[i] * 1.3))
        g2[i] = (0 + (largeurGrandeJauge[i] * 1.3))
    } else {
        r2[i] = (255 - (largeurGrandeJauge[i] * 2.55))
        g2[i] = (0 + (largeurGrandeJauge[i] * 2.55))
    }
    // On applique finalement le style (couleur et transparence) aux grandeJauges avec les valeurs définies ci-dessus. La transparence commence à 0.75 car des valeurs trop basses renvoient des couleurs claires sur du blanc.
    grandeJauges[i].style.backgroundColor = `rgba(
        ${r2[i]},
        ${g2[i]},
        0,
        ${0.75 + (largeurGrandeJauge[i] / 400)}
        )`;
} -->


<!-- PHP :
$javascript = 75;
$php = 65;
$integration = 70;
$symfony = 70;
$react = 40;
$node = 60;
$poo = 55;
$securite = 35;
$debug = 80;
$vsc = 90;

$ui = 40;
$ux = 30;
$graphisme = 55;
$culture = 75;
$photoshop = 60;
$office = 55;

$anglais = 93;
$espagnol = 55;

// Permet d'avoir une variable prenant en compte l'épaisseur de la bordure des "scales" afin de pouvoir calculer exactement la largeur max des jauges qui les remplissent, pour la variable largeurJauge
$borderScales = 1; -->


</html>